/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Common.DoNothingCommand;
import Common.NavigateToCommand;
import Common.TransactionCommand;
import Controller.UIHandler;
import PaymentOptions.AmericanExpress;
import PaymentOptions.MasterCard;
import PaymentOptions.PayPal;
import PaymentOptions.PaymentFactory;
import PaymentOptions.PaymentValidatonVisitor;
import PaymentOptions.Visa;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Dev Mode
 */
public class Pay extends javax.swing.JPanel {
    private UIHandler uiHandler;
    private javax.swing.JFrame frame;

    /**
     * Creates new form PayPanel
     */
    public Pay(JPanel panel, JFrame frame) {
         this.frame = frame;
        this.uiHandler = uiHandler;
         Pay = new CommandJbutton(new DoNothingCommand());
        initComponents();
    }
        public Pay(JFrame frame, JPanel panel, UIHandler uiHandler) {
         this.frame = frame;
        this.uiHandler = uiHandler;
        Pay = new CommandJbutton(new DoNothingCommand());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        paymentSelection = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jPasswordField.setVisible(false);
        jLabel2.setVisible(false);
        cardNumber = new javax.swing.JTextField();
        cardNumber.setToolTipText("");
        cardNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardNumberActionPerformed(evt);
            }
        });

        Pay.setText("Pay");
        Pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        paymentSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Visa", "MasterCard", "American Express", "PayPal" }));
        paymentSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentSelectionActionPerformed(evt);
            }
        });

        jLabel1.setText("Card Number");

        jLabel2.setText("Password");

        jPasswordField.setText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(Pay))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(paymentSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cardNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(jPasswordField))))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(paymentSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(Pay)
                .addGap(88, 88, 88))
        );
    }// </editor-fold>                        
    
    private void cardNumberActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:

    }   
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        PaymentFactory paymentFactory=new PaymentFactory();
        PaymentValidatonVisitor visitor=new PaymentValidatonVisitor();
        if(paymentSelection.getSelectedItem()=="Visa"){
           Visa visa= paymentFactory.getVisa(cardNumber.getText());
            visa.accept(visitor);
             Pay.setCommand(new TransactionCommand(uiHandler,visa.getValidity()));
        }
        else if(paymentSelection.getSelectedItem()=="MasterCard"){
            MasterCard mastercard =paymentFactory.getMasterCard(cardNumber.getText());
            mastercard.accept(visitor);
             Pay.setCommand(new TransactionCommand(uiHandler,mastercard.getValidity()));
        }
        else if(paymentSelection.getSelectedItem()=="American Express"){
            AmericanExpress americanExpress=paymentFactory.getAmericanExpress(cardNumber.getText());
            americanExpress.accept(visitor);
             Pay.setCommand(new TransactionCommand(uiHandler,americanExpress.getValidity()));
        }
        else if(paymentSelection.getSelectedItem()=="PayPal"){
            PayPal payPal =paymentFactory.getPayPal(cardNumber.getText(), String.valueOf(jPasswordField.getPassword()));
            payPal.accept(visitor);
             Pay.setCommand(new TransactionCommand(uiHandler,payPal.getValidity()));
        }
        Pay.execute();
        Pay.setCommand(new NavigateToCommand(new ProductListingAdapted(frame,this,uiHandler),frame));
        Pay.execute();
    }                                        
    private void paymentSelectionActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
        if(paymentSelection.getSelectedItem()=="Visa"){
            jPasswordField.setVisible(false);
            jLabel2.setVisible(false);
            jLabel1.setText("Card Number");
        }
        else if(paymentSelection.getSelectedItem()=="MasterCard"){
            jPasswordField.setVisible(false);
            jLabel2.setVisible(false);
            jLabel1.setText("Card Number");
        }
        else if(paymentSelection.getSelectedItem()=="American Express"){
            jPasswordField.setVisible(false);
            jLabel2.setVisible(false);
            jLabel1.setText("Card Number");
        }
        else if(paymentSelection.getSelectedItem()=="PayPal"){
            jPasswordField.setVisible(true);
            jLabel2.setVisible(true);
            jLabel1.setText("Email");
        }
    }           

    // Variables declaration - do not modify                     
    private CommandJbutton Pay;
    private javax.swing.JTextField cardNumber;
       private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JComboBox<String> paymentSelection;
    // End of variables declaration                   
}
