package UI;

import Common.DoNothingCommand;
import Common.NavigateToCommand;
import Controller.UIHandler;
import Memento.CareTaker;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Vilius
 */
public class ProductPanelAdapted extends javax.swing.JPanel {

    public UIHandler uiHandler;
    private JFrame frame;
    private String productName;
    
    public ProductPanelAdapted(JFrame mainFrame, UIHandler uiHandler, String productName) {
        this.frame = frame;
        this.uiHandler = uiHandler;
        this.productName = productName;
         
        cartB = new CommandJbutton (new DoNothingCommand());
        backB = new CommandJbutton (new NavigateToCommand(CareTaker.getInstance().get(),mainFrame));
        initComponents();
        
        listProductInfo(productName);
    }
    
    public ProductPanelAdapted(JFrame frame, JPanel panel, UIHandler uiHandler, String productName) {
        this.frame = frame;
        this.uiHandler = uiHandler;
        this.productName = productName;
        
        cartB = new CommandJbutton (new DoNothingCommand());
        backB = new CommandJbutton(new NavigateToCommand(panel,frame));
        initComponents();
        
        listProductInfo(productName);
    }
    
    public void listProductInfo(String productName) {
        String productInfo = uiHandler.getProductInfo(productName);
        productInfo = "<html>" + productInfo + "</html>";
        //productInfo.replaceAll("\n", "<br/>");
        productInfoLabel.setText(productInfo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        productInfoLabel = new javax.swing.JLabel();
        backB = new javax.swing.JButton();
        logoutB = new javax.swing.JButton();

        productInfoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        productInfoLabel.setText("Product Info");

        backB.setText("Back");

        logoutB.setText("Add to cart");

        cartB.setText("Logout");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(productInfoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                        .addComponent(backB))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logoutB, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cartB, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productInfoLabel)
                    .addComponent(backB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cartB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                .addComponent(logoutB)
                .addContainerGap())
        );
    }// </editor-fold>                        


    // Variables declaration - do not modify    
    private CommandJbutton Back;
    private javax.swing.JButton backB;
    private javax.swing.JButton logoutB;
    private CommandJbutton cartB;
    private javax.swing.JLabel productInfoLabel;
    // End of variables declaration                   
}
